### ISSUE TITLE
Copy some of your code?

### ISSUE THREAD

**Issue by Prathik-Jain** [BitKnitting/flutter_adafruit_mqtt#2]
Hi @BitKnitting.

We are planning to use the `mqtt_client` flutter library, which also pointed me here. 

Since I do not see any kind on license on this repo, I was wondering if I could copy some basic code?

Thanks :smile:

**Comment by BitKnitting** [comment]
Hi!
Thanks very much for your thoughtfulness.  If possible, could you please:
- credit me (Margaret Johnson)
- find many things to smile about

kind regards!
